
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef GUTENPRINTUI_TYPE_BUILTINS_H
#define GUTENPRINTUI_TYPE_BUILTINS_H

#include <glib-object.h>

G_BEGIN_DECLS
/* enumerations from "curve.h" */
GType stpui_curve_type_get_type (void);
#define STPUI_TYPE_CURVE_TYPE (stpui_curve_type_get_type())
/* enumerations from "gutenprintui.h" */
GType orient_t_orient_t_get_type (void);
#define STPUI_TYPE_ORIENT_T (orient_t_orient_t_get_type())
GType command_t_command_t_get_type (void);
#define STPUI_TYPE_COMMAND_T (command_t_command_t_get_type())
G_END_DECLS

#endif /* GUTENPRINTUI_TYPE_BUILTINS_H */

/* Generated data ends here */

